### ISSUE TITLE
Changes to Aide-clinician documentation and question for Lu

### ISSUE THREAD

**Issue by JillJarvis** [AI4VBH/AIDE#37]
**Aide-clinician**

- [ ] @JoeBatt1989 Make sure table of contents formatting across sections is consistent - before make table of contents here Haleema to check with Lu (see below)
- [x] @heyhaleema is currently blocker - check with Lu about how table of contents translates /would be used in Jupyter books

**Comment by heyhaleema** [comment]
@Lucrezia-Cester For the table of contents/dropdown per page, is it just a matter of formatting the sections, subsections, etc. correctly?

**Comment by Lucrezia-Cester** [comment]
Basically as it is currently set up at the moment, the table of content is structured in this way so that through github action the site is updated automatically each time anything is edited. 

If we want to have a table of content to the site, split into different sections, then we would have to manually update the toc.yml file each time a new .MD file (which would represent a subsection) is added.

Let me know how you would like for the table of content to be restructured and I'll let you know if it is possible.

**Comment by Lucrezia-Cester** [comment]
Hi @JillJarvis, @JoeBatt1989, @heyhaleema, 

If you give me the ok on this, I'll restructured the TOC to mimic this https://ubc-dsci.github.io/jupyterdays/sessions/beuzen/jupyter_book_tutorial.html

Originally I didn't do this bc I had created a GitHub action that would automatically update the site every time an edit was made so that it didn't have to be done manually, but I can improve the GitHub action to reflect this new formatting of the TOC if you prefer it to be formatted this way. 

Please let me know soon so I can start working on this.

**Comment by heyhaleema** [comment]
Thanks, @Lucrezia-Cester, I'm personally in favour of that approach and you starting development whilst @JoeBatt1989  and I work on updating the content.

**Comment by Lucrezia-Cester** [comment]
@heyhaleema cheers

**Comment by heyhaleema** [comment]
@JillJarvis @JoeBatt1989 I've updated this issue title since it's now been closed with @Lucrezia-Cester's PR #41.
@Lucrezia-Cester Is there a need for the .md files to contain their own ToC, e.g. for subsections? Or does just adding subsections automatically get reflected in the Jupyter Book?

**Comment by JillJarvis** [comment]
> Thanks, @Lucrezia-Cester, I'm personally in favour of that approach and you starting development whilst @JoeBatt1989 and I work on updating the content.

Haleema is the person that needs to ok this, I don't need to. So as Haleema has replied here then we're all good :-)
